name:                RWTH-lectures
version:             0.1.0.0
github:              "lenchevskii/RWTH-lectures"
license:             BSD3
author:              "Dmitry Lenchevski"
maintainer:          "dima.lenchevskii@gmail.com"
copyright:           "2020 Dmitry Lenchevski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Functions used in lectures (Aachen Technical University)
# category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/RWTH-lectures#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  RWTH-lectures-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RWTH-lectures

tests:
  RWTH-lectures-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RWTH-lectures
